# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hongjiyin_ctpj.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QRegExp
from PyQt5.QtWidgets import QWidget, QMessageBox, QFileDialog, QApplication, QDialog
from PyQt5.QtGui import QRegExpValidator, QIntValidator
import os


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 504)

        # 设置标签字体
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        # 设置输入框字体
        font_le = QtGui.QFont()
        font_le.setPointSizeF(11)
        font_le.setBold(True)
        font_le.setWeight(75)

        # 按钮
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 400, 391, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.run_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.run_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.run_btn.setObjectName("run_btn")
        self.run_btn.setStyleSheet("QPushButton{\n"
                                   "    background:#2AC28F;\n"
                                   "    color:white;\n"
                                   "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                   "}\n"
                                   "QPushButton:hover{                    \n"
                                   "    background:#99CC99;\n"
                                   "}\n")
        self.horizontalLayout_5.addWidget(self.run_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.cancel_btn.setObjectName("cancel_btn")
        self.cancel_btn.setStyleSheet("QPushButton{\n"
                                      "    background:rgb(241, 84, 84);\n"
                                      "    color:white;\n"
                                      "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                      "}\n"
                                      "QPushButton:hover{                    \n"
                                      "    background:#FF6666;\n"
                                      "}\n")
        self.horizontalLayout_5.addWidget(self.cancel_btn)
        # 起始路径
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(71, 53, 561, 321))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ori_label = QtWidgets.QLabel(self.widget)
        self.ori_label.setObjectName("ori_label")
        self.ori_label.setFont(font)
        self.horizontalLayout.addWidget(self.ori_label)
        self.ori_LE = QtWidgets.QLineEdit(self.widget)
        self.ori_LE.setObjectName("ori_LE")
        self.ori_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.ori_LE.setFont(font_le)
        self.horizontalLayout.addWidget(self.ori_LE)
        self.ori_tbtn = QtWidgets.QToolButton(self.widget)
        self.ori_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.ori_tbtn.setObjectName("ori_tbtn")
        self.horizontalLayout.addWidget(self.ori_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        # 列表文件
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_label = QtWidgets.QLabel(self.widget)
        self.list_label.setObjectName("list_label")
        self.list_label.setFont(font)
        self.horizontalLayout_2.addWidget(self.list_label)
        self.list_LE = QtWidgets.QLineEdit(self.widget)
        self.list_LE.setObjectName("list_LE")
        self.list_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.list_LE.setFont(font_le)
        self.horizontalLayout_2.addWidget(self.list_LE)
        self.list_tbtn = QtWidgets.QToolButton(self.widget)
        self.list_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.list_tbtn.setObjectName("list_tbtn")
        self.horizontalLayout_2.addWidget(self.list_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # 结果路径
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.result_label = QtWidgets.QLabel(self.widget)
        self.result_label.setObjectName("result_label")
        self.result_label.setFont(font)
        self.horizontalLayout_3.addWidget(self.result_label)
        self.result_LE = QtWidgets.QLineEdit(self.widget)
        self.result_LE.setObjectName("result_LE")
        self.result_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.result_LE.setFont(font_le)
        self.horizontalLayout_3.addWidget(self.result_LE)
        self.result_tbtn = QtWidgets.QToolButton(self.widget)
        self.result_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.result_tbtn.setObjectName("result_tbtn")
        self.horizontalLayout_3.addWidget(self.result_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        # 纠错模型
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.model_lb = QtWidgets.QLabel(self.widget)
        self.model_lb.setObjectName("model_lb")
        self.model_lb.setFont(font)
        self.horizontalLayout_4.addWidget(self.model_lb)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(100)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.label.setFont(font)
        self.horizontalLayout_4.addWidget(self.label)
        self.count_LE = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_LE.sizePolicy().hasHeightForWidth())
        self.count_LE.setSizePolicy(sizePolicy)
        self.count_LE.setMinimumSize(QtCore.QSize(10, 30))
        self.count_LE.setMaximumSize(QtCore.QSize(50, 16777215))
        self.count_LE.setObjectName("lineEdit")
        self.count_LE.setFont(font_le)
        self.horizontalLayout_4.addWidget(self.count_LE)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        # 线程数
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.thread_label = QtWidgets.QLabel(self.widget)
        self.thread_label.setObjectName("thread_label")
        self.thread_label.setFont(font)
        self.horizontalLayout_6.addWidget(self.thread_label)
        self.thread_LE = QtWidgets.QLineEdit(self.widget)
        self.thread_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.thread_LE.setFont(font_le)
        self.horizontalLayout_6.addWidget(self.thread_LE)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.ori_tbtn.clicked.connect(lambda: self.choose_path(self.ori_LE))
        self.list_tbtn.clicked.connect(lambda: self.open_file(self.list_LE))
        self.result_tbtn.clicked.connect(lambda: self.choose_path(self.result_LE))

        self.cancel_btn.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.run_btn.setText(_translate("Dialog", "运行"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))
        self.ori_label.setText(_translate("Dialog", "起始路径："))
        self.ori_tbtn.setText(_translate("Dialog", "..."))
        self.list_label.setText(_translate("Dialog", "列表文件："))
        self.list_tbtn.setText(_translate("Dialog", "..."))
        self.result_label.setText(_translate("Dialog", "结果路径："))
        self.result_tbtn.setText(_translate("Dialog", "..."))
        self.model_lb.setText(_translate("Dialog", "纠错模型："))
        self.label.setText(_translate("Dialog", "纠错次数："))
        self.thread_label.setText(_translate("Dialog", "线程数："))

    def open_file(self, lineEdit):
        """
        选择具体的文件
        :param lineEdit: 将内容写入具体的文本框
        :return:
        """
        directory1 = QFileDialog.getOpenFileName(self.Dialog, "选取文件", "./")
        lineEdit.setText(directory1[0])

    def choose_path(self, lineEdit):
        """
        选择结果存放路径
        :param lineEdit: 将内容写入具体的文本框
        :return:
        """
        directory1 = QFileDialog.getExistingDirectory(self.Dialog, "选取文件夹", "./")
        lineEdit.setText(directory1)

    def receive_param(self):
        """
        接收子窗口中的所有参数，并发送给主窗口
        :return: 当前工作路径
        """
        # 样品列表文件
        sample_list = self.deal_sample()
        # 起始路径
        start_file = self.start_LE.text()
        # 参考序列
        xvlie_path = self.xvlie_LE.text()
        # 测序类型
        cexv_type = ''
        if self.single_RB.isChecked():
            cexv_type = 'SE'
        elif self.double_RB.isChecked():
            cexv_type = 'PE'
        # 线程数
        threads_ = self.thread_LE.text()
        # SNP阈值
        snp = self.snp_LE.text()
        # 测序深度阈值
        depth = self.depth_LE.text()
        # 测序质量阈值
        quality = self.quality_LE.text()

        # 判断fastq文件中的第一个字符为'>'并且有且仅有一个
        if os.path.isfile(xvlie_path):
            try:
                with open(xvlie_path, 'r') as f:
                    file_content = f.read()
                # 文件的首个字符为'>'
                findex = file_content.index('>')
                # 文件中有且只有一个‘>’
                count = file_content.count('>')
            except Exception as e:
                print(f'文件读取失败：{e}')
                findex = 1
                count = 2
        else:
            findex = 1
            count = 2

        if not start_file or not sample_list or not threads_ or not depth or not quality:
            QMessageBox.warning(self, '警告', '参数不能为空！', QMessageBox.Ok)
        elif findex != 0 or count != 1:
            QMessageBox.warning(self, '警告', '参考序列文件格式存在错误', QMessageBox.Ok)
        else:
            self.signal = 1
            # 根据起文件夹名称作为任务名称
            task_nm = start_file.split('/')[-1] if '/' in start_file else start_file
            # 获取当前窗口标题进行任务区分
            task_type = self.Dialog.windowTitle()
            # 由于主页面需要显示（样品名称、barcode）参数，所以在子页面这两个参数必须存在
            parmas = {
                'task_type': task_type,
                'task_name': task_nm,
                'sample_list': sample_list,
                'barcode_list': '',
                'work_file': start_file,
                'cexv_type': cexv_type,
                'xvlie_file': xvlie_path,
                'snp': snp,
                'threads': threads_,
                'depth': depth,
                'quality': quality,
            }
            # print(parmas)
            self.paramSignal.emit(parmas)
            self.Dialog.close()

    def send_start_sig(self):
        """
        发送启动信号给主界面，来调用命令运行程序
        :return:
        """
        # print(f'发送的信号为：{self.signal}')
        self.startSignal.emit(self.signal)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # 实例化主窗口
    main = QDialog()
    main_ui = Ui_Dialog()
    main_ui.setupUi(main)
    # 显示
    main.show()
    # QMessageBox.warning()
    sys.exit(app.exec_())