# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xinguan_suyuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QRegExp
from PyQt5.QtWidgets import QWidget, QMessageBox, QFileDialog, QApplication, QDialog
import os
from configparser import ConfigParser


exepath = os.getcwd().replace('\\', '/')
config = ConfigParser()
config.read(f'{exepath}/G_CONFIG/config.ini'.replace('/G_UI', ''), encoding='utf-8')




class Ui_Dialog(QWidget):

    paramSignal = pyqtSignal(dict)
    startSignal = pyqtSignal(int)
    signal = 0

    def __init__(self, data_list):
        super(Ui_Dialog, self).__init__()
        self.data_list = data_list

    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 450)

        # 设置标签字体
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        # 设置输入框字体
        font_le = QtGui.QFont()
        font_le.setPointSizeF(11)
        font_le.setBold(True)
        font_le.setWeight(75)

        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(41, 30, 730, 400))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # 序列文件
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xvlie_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xvlie_LB.sizePolicy().hasHeightForWidth())
        self.xvlie_LB.setSizePolicy(sizePolicy)
        self.xvlie_LB.setMinimumSize(QtCore.QSize(113, 0))
        self.xvlie_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xvlie_LB.setObjectName("xvlie_LB")
        self.xvlie_LB.setFont(font)
        self.horizontalLayout.addWidget(self.xvlie_LB)
        self.xvlie_LE = QtWidgets.QLineEdit(self.widget)
        self.xvlie_LE.setObjectName("xvlie_LE")
        self.xvlie_LE.setFont(font_le)
        self.xvlie_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout.addWidget(self.xvlie_LE)
        self.xvlie_tbtn = QtWidgets.QToolButton(self.widget)
        self.xvlie_tbtn.setObjectName("xvlie_tbtn")
        self.xvlie_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.horizontalLayout.addWidget(self.xvlie_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        # 序列信息
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.info_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_LB.sizePolicy().hasHeightForWidth())
        self.info_LB.setSizePolicy(sizePolicy)
        self.info_LB.setMinimumSize(QtCore.QSize(113, 0))
        self.info_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info_LB.setObjectName("info_LB")
        self.info_LB.setFont(font)
        self.horizontalLayout_2.addWidget(self.info_LB)
        self.info_LE = QtWidgets.QLineEdit(self.widget)
        self.info_LE.setObjectName("info_LE")
        self.info_LE.setFont(font_le)
        self.info_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_2.addWidget(self.info_LE)
        self.info_tbtn = QtWidgets.QToolButton(self.widget)
        self.info_tbtn.setObjectName("info_tbtn")
        self.info_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.horizontalLayout_2.addWidget(self.info_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # 结果路径
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.result_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_label.sizePolicy().hasHeightForWidth())
        self.result_label.setSizePolicy(sizePolicy)
        self.result_label.setMinimumSize(QtCore.QSize(113, 0))
        self.result_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_label.setObjectName("result_label")
        self.result_label.setFont(font)
        self.horizontalLayout_3.addWidget(self.result_label)
        self.result_LE = QtWidgets.QLineEdit(self.widget)
        self.result_LE.setObjectName("result_LE")
        self.result_LE.setFont(font_le)
        self.result_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_3.addWidget(self.result_LE)
        self.result_tbtn = QtWidgets.QToolButton(self.widget)
        self.result_tbtn.setObjectName("result_tbtn")
        self.result_tbtn.setMaximumSize(QtCore.QSize(30, 28))
        self.horizontalLayout_3.addWidget(self.result_tbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        # 每样品序列数
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.count_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_LB.sizePolicy().hasHeightForWidth())
        self.count_LB.setSizePolicy(sizePolicy)
        self.count_LB.setMinimumSize(QtCore.QSize(100, 0))
        self.count_LB.setObjectName("count_LB")
        self.count_LB.setFont(font)
        self.horizontalLayout_4.addWidget(self.count_LB)
        self.count_LE = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_LE.sizePolicy().hasHeightForWidth())
        self.count_LE.setSizePolicy(sizePolicy)
        self.count_LE.setObjectName("count_LE")
        self.count_LE.setFont(font_le)
        self.count_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_4.addWidget(self.count_LE)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        # 新冠数据库
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_4")
        self.database_lb = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.database_lb.sizePolicy().hasHeightForWidth())
        self.database_lb.setSizePolicy(sizePolicy)
        self.database_lb.setMinimumSize(QtCore.QSize(100, 0))
        self.database_lb.setObjectName("model_lb")
        self.database_lb.setFont(font)
        self.database_lb.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.database_lb)
        self.database_box = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.database_box.sizePolicy().hasHeightForWidth())
        self.database_box.setSizePolicy(sizePolicy)
        self.database_box.setObjectName("database_box")
        self.database_box.setFont(font_le)
        self.database_box.addItems(self.data_list)
        self.database_box.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_5.addWidget(self.database_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_5")
        self.run_btn = QtWidgets.QPushButton(self.widget)
        self.run_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.run_btn.setObjectName("run_btn")
        self.run_btn.setStyleSheet("QPushButton{\n"
                                   "    background:#2AC28F;\n"
                                   "    color:white;\n"
                                   "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                   "}\n"
                                   "QPushButton:hover{                    \n"
                                   "    background:#99CC99;\n"
                                   "}\n")
        self.horizontalLayout_6.addWidget(self.run_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.widget)
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.cancel_btn.setObjectName("cancel_btn")
        self.cancel_btn.setStyleSheet("QPushButton{\n"
                                      "    background:rgb(241, 84, 84);\n"
                                      "    color:white;\n"
                                      "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                      "}\n"
                                      "QPushButton:hover{                    \n"
                                      "    background:#FF6666;\n"
                                      "}\n")
        self.horizontalLayout_6.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.xvlie_tbtn.clicked.connect(lambda: self.open_file(self.xvlie_LE))
        self.info_tbtn.clicked.connect(lambda: self.open_file(self.info_LE))
        self.result_tbtn.clicked.connect(lambda: self.choose_path(self.result_LE))

        self.run_btn.clicked.connect(self.receive_param)
        self.run_btn.clicked.connect(self.send_start_sig)
        self.cancel_btn.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.xvlie_LB.setText(_translate("Dialog", "序列文件："))
        self.xvlie_tbtn.setText(_translate("Dialog", "..."))
        self.info_LB.setText(_translate("Dialog", "序列信息："))
        self.info_tbtn.setText(_translate("Dialog", "..."))
        self.result_label.setText(_translate("Dialog", "结果路径："))
        self.result_tbtn.setText(_translate("Dialog", "..."))
        self.count_LB.setText(_translate("Dialog", "每样品序列数："))
        self.database_lb.setText(_translate("Dialog", "新冠数据库："))
        self.run_btn.setText(_translate("Dialog", "运行"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))

    def open_file(self, lineEdit):
        """
        选择具体的文件
        :param lineEdit: 将内容写入具体的文本框
        :return:
        """
        directory1 = QFileDialog.getOpenFileName(self.Dialog, "选取文件", "./")
        lineEdit.setText(directory1[0])

    def choose_path(self, lineEdit):
        """
        选择具体的文件路径
        :param lineEdit: 将内容写入具体的文本框
        :return:
        """
        directory1 = QFileDialog.getExistingDirectory(self.Dialog, "选取文件夹", "./")
        lineEdit.setText(directory1)


    def receive_param(self):
        """
        接收子窗口中的所有参数，并发送给主窗口
        :return: 当前工作路径
        """
        # 序列文件
        xvlie_file = self.xvlie_LE.text()
        # 序列信息
        xvlie_info = self.info_LE.text()
        # 结果路径
        result_path = self.result_LE.text()
        # 每样品序列数
        count = self.count_LE.text()
        # 新冠数据库
        database = self.database_box.currentText()

        if not xvlie_file or not xvlie_info or not count or not result_path or not database:
            QMessageBox.warning(self, '警告', '参数不能为空！', QMessageBox.Ok)
        else:
            self.signal = 1
            # 根据起文件夹名称作为任务名称
            task_nm = xvlie_file.split('/')[-1] if '/' in xvlie_file else xvlie_file
            # 获取当前窗口标题进行任务区分
            task_type = self.Dialog.windowTitle()
            # 由于主页面需要显示（样品名称、barcode）参数，所以在子页面这两个参数必须存在
            parmas = {
                'task_type': task_type,
                'task_name': task_nm,
                'sample_list': '',
                'barcode_list': '',
                'result_path': result_path,
                'database': database,
                'xvlie_file': xvlie_file,
                'xvlie_info': xvlie_info,
                'count': count
            }
            # print(parmas)
            self.paramSignal.emit(parmas)
            self.Dialog.close()

    def send_start_sig(self):
        """
        发送启动信号给主界面，来调用命令运行程序
        :return:
        """
        # print(f'发送的信号为：{self.signal}')
        self.startSignal.emit(self.signal)


if __name__ == '__main__':
    con_model = config.get('SARS2_analyze', 'database_list')
    data_list = con_model.split(',')

    app = QApplication(sys.argv)
    # 实例化主窗口
    main = QDialog()
    main_ui = Ui_Dialog(data_list)
    main_ui.setupUi(main)
    # 显示
    main.show()
    # QMessageBox.warning()
    sys.exit(app.exec_())

