# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '新冠污水.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import re
import sys
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, QRegExp
from PyQt5.QtWidgets import QWidget, QMessageBox, QFileDialog, QApplication, QDialog
from PyQt5.QtGui import QRegExpValidator, QIntValidator
import os
from configparser import ConfigParser


# 新冠病毒污水分析


exepath = os.getcwd().replace('\\', '/')
config = ConfigParser()
config.read(f'{exepath}/G_CONFIG/config.ini'.replace('/G_UI', ''), encoding='utf-8')


class Ui_Dialog(QWidget):

    paramSignal = pyqtSignal(dict)
    startSignal = pyqtSignal(int)
    signal = 0

    def __init__(self, yw_list):
        super(Ui_Dialog, self).__init__()
        self.yw_list = yw_list

    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        # Dialog.resize(830, 410)
        Dialog.setFixedSize(830, 400)
        # Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget = QtWidgets.QWidget(Dialog)

        # 设置标签字体
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)

        # 设置输入框字体
        font_le = QtGui.QFont()
        font_le.setPointSizeF(11)
        font_le.setBold(True)
        font_le.setWeight(75)

        self.widget.setGeometry(QtCore.QRect(70, 40, 720, 300))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # 起始路径
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ori_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ori_LB.sizePolicy().hasHeightForWidth())
        self.ori_LB.setSizePolicy(sizePolicy)
        self.ori_LB.setMinimumSize(QtCore.QSize(100, 30))
        # self.ori_LB.setMaximumSize(QtCore.QSize(10000, 10000))
        self.ori_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ori_LB.setObjectName("ori_LB")
        self.ori_LB.setFont(font)
        self.horizontalLayout.addWidget(self.ori_LB)
        self.ori_LE = QtWidgets.QLineEdit(self.widget)
        self.ori_LE.setObjectName("ori_LE")
        self.ori_LE.setFont(font_le)
        self.ori_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout.addWidget(self.ori_LE)
        self.ori_TB = QtWidgets.QToolButton(self.widget)
        self.ori_TB.setObjectName("ori_TB")
        self.ori_TB.setMaximumSize(QtCore.QSize(30, 28))
        self.horizontalLayout.addWidget(self.ori_TB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        # 引物
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.yw_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yw_LB.sizePolicy().hasHeightForWidth())
        self.yw_LB.setSizePolicy(sizePolicy)
        self.yw_LB.setMinimumSize(QtCore.QSize(100, 30))
        # self.yw_LB.setMaximumSize(QtCore.QSize(10000, 10000))
        self.yw_LB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yw_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yw_LB.setObjectName("yw_LB")
        self.yw_LB.setFont(font)
        self.horizontalLayout_2.addWidget(self.yw_LB)
        self.yw_CB = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yw_CB.sizePolicy().hasHeightForWidth())
        self.yw_CB.setSizePolicy(sizePolicy)
        self.yw_CB.setMinimumSize(QtCore.QSize(0, 30))
        self.yw_CB.setObjectName("yw_CB")
        self.yw_CB.setFont(font_le)
        self.yw_CB.addItems(self.yw_list)
        self.horizontalLayout_2.addWidget(self.yw_CB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        # 结果路径
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.result_LB = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_LB.sizePolicy().hasHeightForWidth())
        self.result_LB.setSizePolicy(sizePolicy)
        self.result_LB.setMinimumSize(QtCore.QSize(100, 30))
        # self.result_LB.setMaximumSize(QtCore.QSize(10000, 10000))
        self.result_LB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result_LB.setObjectName("result_LB")
        self.result_LB.setFont(font)
        self.horizontalLayout_3.addWidget(self.result_LB)
        self.result_LE = QtWidgets.QLineEdit(self.widget)
        self.result_LE.setObjectName("result_LE")
        self.result_LE.setFont(font_le)
        self.result_LE.setMinimumSize(QtCore.QSize(0, 30))
        self.horizontalLayout_3.addWidget(self.result_LE)
        self.result_TB = QtWidgets.QToolButton(self.widget)
        self.result_TB.setObjectName("result_TB")
        self.result_TB.setMaximumSize(QtCore.QSize(30, 28))
        self.horizontalLayout_3.addWidget(self.result_TB)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_btn = QtWidgets.QPushButton(self.widget)
        self.run_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.run_btn.setObjectName("run_btn")
        self.run_btn.setStyleSheet("QPushButton{\n"
                                   "    background:#2AC28F;\n"
                                   "    color:white;\n"
                                   "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                   "}\n"
                                   "QPushButton:hover{                    \n"
                                   "    background:#99CC99;\n"
                                   "}\n")
        self.horizontalLayout_4.addWidget(self.run_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.widget)
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.cancel_btn.setObjectName("cancel_btn")
        self.cancel_btn.setStyleSheet("QPushButton{\n"
                                      "    background:rgb(241, 84, 84);\n"
                                      "    color:white;\n"
                                      "    box-shadow: 1px 1px 3px rgba(0,0,0,0.3);font-size:20px;border-radius: 3px;font-family: 思源黑体;\n"
                                      "}\n"
                                      "QPushButton:hover{                    \n"
                                      "    background:#FF6666;\n"
                                      "}\n")
        self.horizontalLayout_4.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.result_TB.clicked.connect(lambda: self.choose_path(self.result_LE))
        self.ori_TB.clicked.connect(lambda: self.choose_path(self.ori_LE))

        self.run_btn.clicked.connect(self.receive_param)
        self.run_btn.clicked.connect(self.send_start_sig)
        self.cancel_btn.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ori_LB.setText(_translate("Dialog", "起始路径："))
        self.ori_TB.setText(_translate("Dialog", "..."))
        self.yw_LB.setText(_translate("Dialog", "引物："))
        self.result_LB.setText(_translate("Dialog", "结果路径："))
        self.result_TB.setText(_translate("Dialog", "..."))
        self.run_btn.setText(_translate("Dialog", "运行"))
        self.cancel_btn.setText(_translate("Dialog", "取消"))

    def choose_path(self, lineEdit):
        """
        选择结果存放路径
        :param lineEdit: 将内容写入具体的文本框
        :return:
        """
        directory1 = QFileDialog.getExistingDirectory(self.Dialog, "选取文件夹", "./")
        lineEdit.setText(directory1)


    def receive_param(self):
        """
        接收子窗口中的所有参数，并发送给主窗口
        :return: 当前工作路径
        """
        # 起始文件
        ori_path = self.ori_LE.text()
        #引物
        yw_data = self.yw_CB.currentText()
        # 结果路径
        result_path = self.result_LE.text()

        if not ori_path or not result_path:
            QMessageBox.warning(self, '警告', '参数不能为空！', QMessageBox.Ok)
        else:
            self.signal = 1
            # 根据起文件夹名称作为任务名称
            result = re.findall(r'.*/(.*?)\..*', ori_path)
            task_nm = result[0] if result else str(int(time.time()*1000))
            # 获取当前窗口标题进行任务区分
            task_type = self.Dialog.windowTitle()
            # 由于主页面需要显示（样品名称、barcode）参数，所以在子页面这两个参数必须存在
            parmas = {
                'task_type': task_type,
                'task_name': task_nm,
                'sample_list': '',
                'barcode_list': '',
                'result_path': result_path,
                'ori_path': ori_path,
                'yw_data': yw_data
            }
            # print(parmas)
            self.paramSignal.emit(parmas)
            self.Dialog.close()

    def send_start_sig(self):
        """
        发送启动信号给主界面，来调用命令运行程序
        :return:
        """
        # print(f'发送的信号为：{self.signal}')
        self.startSignal.emit(self.signal)


if __name__ == '__main__':
    con_model = config.get('SARS2_analyze', 'primer_list')
    yw_list = con_model.split(',')

    app = QApplication(sys.argv)
    # 实例化主窗口
    main = QDialog()
    main_ui = Ui_Dialog(yw_list)
    main_ui.setupUi(main)
    # 显示
    main.show()
    # QMessageBox.warning()
    sys.exit(app.exec_())
